<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ips = [
            "Acornhoek 1",
            "ACORNHOEK 2",
            "ALBERTON",
            "ALEX1",
            "ATTERDIGEVILLE1",
            "Barberton 1",
            "BELA BELA",
            "BELFAST1 ",
            "BELLSTAR JUNCTION",
            "BENONI 1 ",
            "BETHAL 1",
            "BLOEMFONTEIN 1",
            "BLOEMFONTEIN 2",
            "BOCHUM 1 ",
            "BOKSBURG 1",
            "BOKSBURG 2 ",
            "BOTSHABELO",
            "BRACKENFELL 1",
            "BRAKPAN 1 ",
            "BRITS 1",
            "Bronkhorstspruit 1",
            "BURGERSFORT 1 ",
            "BURGERSFORT 2 ",
            "BURGERSFORT 3",
            "BURGERSFORT 4 ",
            "BURGERSFORT 5 ",
            "BURGERSFORT 6",
            "BURGERSFORT 7 ",
            "BUSHBUCKRIDGE 1 ",
            "BUSHBUCKRIDGE2",
            "CARLETONVILLE",
            "CAROLINA 1 ",
            "CHUMA MALL",
            "Cosmo Mall",
            "CULLINAN 1",
            "DELMAS 1",
            "DUNDEE 1 ",
            "Durban 1",
            "Durban Pine Parkade",
            "EDENDALE  MALL",
            "EDENVALE 1",
            "Ellisras 1",
            "ELUKWATINI 1",
            "EMPANGENI1",
            "EMPANGENI2",
            "ERMELO 1 ",
            "ERMELO 2",
            "ESHOWE",
            "EVANDER 1 ",
            "Fraaiuitzicht ",
            "GA-RANKUWA 1",
            "GERMISTON 1 ",
            "GIYANI 1 ",
            "GRAND PARADE ",
            "GRASKOP 1",
            "GROBLERSDAL 1 ",
            "GROBLERSDAL 2",
            "GUGULETHU",
            "HAMMANSKRAAL 1",
            "HARRISMITH",
            "HAZYVIEW 1",
            "HAZYVIEW 2",
            "HEIDELBERG 1 ",
            "HEIDELBERG1",
            "HENDRINA 1 ",
            "HERMANUS 1",
            "ISIPINGO 1 ",
            "JANE FURSE 1 ",
            "JOHANNESBURG 1",
            "JOHANNESBURG 2 ",
            "JOHANNESBURG 3",
            "JOHANNESBURG 4",
            "JOZINI1",
            "KABOKWENI 1 ",
            "KATLEHONG 1",
            "KEMPTON PARK 1 ",
            "KEMPTON PARK 2",
            "KEMPTON PARK 3",
            "KLERKSDORP 1 ",
            "KRIEL 1 ",
            "KROONSTAD",
            "KRUGERSDORP1",
            "KWAMHLANGA 1 ",
            "LADYSMITH 1",
            "LEBOWAKGOMO 1 ",
            "LOUIS TRICHARDT 1",
            "LOUIS TRICHARDT 2",
            "LYDENBURG 1 ",
            "LYDENBURG 2 ",
            "LYDENBURG 3 ",
            "LYDENBURG HQ",
            "MAAKE PLAZA ",
            "MABOPANE  1",
            "MAFIKENG 1",
            "MAFIKENG 2 ",
            "MAFIKENGTEST",
            "MAHWELERENG 1",
            "MALALANE 1 ",
            "MALALANE 2",
            "MAMELODI 1",
            "MAMS MALL",
            "MANDELA PARK",
            "MANKWENG 1",
            "MARBLE HALL 1",
            "MENLYN WOODS HQ",
            "MIDDELBURG 1",
            "MIDDELBURG 2 ",
            "MIDDELBURG 3 ",
            "MIDRAND 1&2",
            "MKUZE1",
            "NAAS 1 ",
            "NABOOMSPRUIT 1 ",
            "NELSPRUIT 1",
            "NELSPRUIT 2",
            "NELSPRUIT 3 ",
            "NELSPRUIT 4",
            "NEWCASTLE 1",
            "NEWCASTLE 2 ",
            "NONGOMA",
            "NORTHAM",
            "NYLSTROOM 1",
            "OGIES 1 ",
            "OK MALL MITCHELLS PLAIN",
            "OLIEVENHOUT 1 ",
            "ORKNEY 1",
            "PAROW 1",
            "PHALABORWA 1 ",
            "PHALABORWA 2",
            "PIET RETIEF 1 ",
            "PIETERMARITZBURG 1",
            "PIETERMARITZBURG 2 ",
            "PIETERMARITZBURG 3 ",
            "PINETOWN 1",
            "PINETOWN 2",
            "POLOKWANE 1 ",
            "POLOKWANE 2 ",
            "POLOKWANE 3 ",
            "POLOKWANE 4 ",
            "POLOKWANE 5",
            "PONGOLA 1",
            "POTCHEFSTROOM 1 ",
            "POTGIETERSRUS 1",
            "POTGIETERSRUS 2",
            "PRETORIA 1 ",
            "PRETORIA 2 ",
            "PRETORIA 3 ",
            "PRETORIA CITY CORNER (PTA 5)",
            "PRETORIA NORTH SECURITY",
            "RANDBURG",
            "RICHARDSBAY 1 ",
            "ROODEPOORT",
            "RUSTENBURG 1 ",
            "RUSTENBURG 2 ",
            "RUSTENBURG 3",
            "RUSTENBURG4",
            "SABIE 1",
            "SASOLBURG 1 ",
            "SEBOKENG 1 ",
            "SECUNDA 1",
            "SECUNDA 2",
            "SKY CITY 1",
            "SOSHANGUVE",
            "SOWETO 1 ",
            "SPRINGS 1 ",
            "STANDERTON 1",
            "STANGER",
            "STATION PLAZA",
            "STEELEDALE",
            "STEELPOORT 1",
            "SUNNYSIDE 1",
            "THABAZIMBI 1",
            "THOHOYANDOU 1",
            "THOHOYANDOU 2",
            "THOHOYANDOU 3 ",
            "THULAMAHASH",
            "Tonga 1",
            "TONGAAT 1",
            "TUGELA FERRY 1",
            "TZANEEN 1 ",
            "TZANEEN 2",
            "ULUNDI1",
            "UMLAZI",
            "VANDERBIJLPARK 1",
            "VEREENIGING 1",
            "Vereeniging 2",
            "VOLKSRUST",
            "VOSLOOSRUS",
            "VRYHEID",
            "WELKOM",
            "WHITE RIVER 1 ",
            "WITBANK 1",
            "WITBANK 2",
            "WITBANK 3 ",
            "WITBANK 4 ",
            "WITBANK 5 ",
            "WITBANK 6",
            "WITBANK 7",
            "WORCESTER 1"];
        foreach($ips as $ip){
            \DB::table('locations')->insert([
                'description' => $ip,
                'longitude' => '-25',
                'latitude' => '28',
                'status' => 0
            ]);
        }


    }
}
